# -*- coding: utf-8 -*-
"""README.DOC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6LpPXWJ0pzZxvj0er2wCdZ2C_w4l0G2

IBM-Project-471-1658738225
Real-Time Communication System Powered by AI for Specially Abled

Team ID: PNT2022TMID30344

Team Leader : Ishwarya .S

Team Member 1:Ananthi . C

Team Member 2:Gomathi.S

Team Member 3:manomozhi . m

Demo link : https://drive.google.com/file/d/1ef1PyawQuHcKwgBXEfllyU_qAZyJLHx5/view?usp=share_link
"""